FROM ruby:4.0.3

WORKDIR /app

ENV BUNDLE_PATH=/usr/local/bundle \
    PATH=/usr/local/bundle/bin:$PATH

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

EXPOSE 3000

CMD ["bash", "-lc", "rm -f tmp/pids/server.pid && bin/rails db:prepare && bin/rails server -b 0.0.0.0 -p 3000"]
